//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class System_Collections_Generic_KeyValuePair_int_TestAccountWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(System.Collections.Generic.KeyValuePair<int,TestAccount>), null, "KeyValuePair_int_TestAccount");
		L.RegFunction("ToString", new LuaCSFunction(ToString));
		L.RegFunction("New", new LuaCSFunction(_CreateSystem_Collections_Generic_KeyValuePair_int_TestAccount));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("Key", new LuaCSFunction(get_Key), null);
		L.RegVar("Value", new LuaCSFunction(get_Value), null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSystem_Collections_Generic_KeyValuePair_int_TestAccount(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				int arg0 = (int)LuaDLL.luaL_checkinteger(L, 1);
				TestAccount arg1 = ToLua.CheckObject<TestAccount>(L, 2);
				System.Collections.Generic.KeyValuePair<int,TestAccount> obj = new System.Collections.Generic.KeyValuePair<int,TestAccount>(arg0, arg1);
				ToLua.PushValue(L, obj);
				return 1;
			}
			else if (count == 0)
			{
				System.Collections.Generic.KeyValuePair<int,TestAccount> obj = new System.Collections.Generic.KeyValuePair<int,TestAccount>();
				ToLua.PushValue(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: System.Collections.Generic.KeyValuePair<int,TestAccount>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			System.Collections.Generic.KeyValuePair<int,TestAccount> obj = ToLua.CheckObject<System.Collections.Generic.KeyValuePair<int,TestAccount>>(L, 1);
			string o = obj.ToString();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Key(IntPtr L)
	{
		System.Collections.Generic.KeyValuePair<int,TestAccount> obj = default(System.Collections.Generic.KeyValuePair<int,TestAccount>);
		try
		{
			obj = ToLua.ToGenericObject<System.Collections.Generic.KeyValuePair<int,TestAccount>>(L, 1);
			int ret = obj.Key;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, obj, "attempt to index Key on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Value(IntPtr L)
	{
		System.Collections.Generic.KeyValuePair<int,TestAccount> obj = default(System.Collections.Generic.KeyValuePair<int,TestAccount>);
		try
		{
			obj = ToLua.ToGenericObject<System.Collections.Generic.KeyValuePair<int,TestAccount>>(L, 1);
			TestAccount ret = obj.Value;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, obj, "attempt to index Value on a nil value");
		}
	}
}

